services:
  - type: web
    env: node
    name: cents-prod-backend
    repo: https://github.com/Adedunmol/cents-typescript.git
    buildCommand: npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: MAILTRAP_USERNAME
        sync: false
      - key: MAILTRAP_PASSWORD
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: REDIS_URL
        fromService:
          name: cents-prod-redis
          type: redis
          property: connectionString

  - type: redis
    name: cents-prod-redis
    ipAllowList: []
    maxmemoryPolicy: noeviction